# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Richard Lin
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  richard.lin at berkeley.edu <br/><br/>

  I'm interested in improving electronics design, by making it more accessible and usable for novices, and more efficient for experts.
  My primary research focuses on board-level design, emphasizing design re-use and abstraction, and blending techniques from the human-computer interaction (HCI), programming languages (PL), and electrical engineering (EE) domains.
  I also continue to work on chip- and FPGA-level digital logic design languages, similarly applying a blend of HCI and PL techniques to produce usable tools. <br/><br/>
  
  I am a postdoc at UCLA, as part of Ankur Mehta's LEMUR lab.
  Previously, I completed my PhD at UC Berkeley, co-advised by by Björn Hartmann and Elad Alon.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ducky64.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: ducky64

logo: DucklingCircleGeneric.png
show_downloads: false

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
